set -o vi
shopt -s histappend
# Location specific aliases and functions
if [ -f $HOME/.bashrc ]; then
  . $HOME/.bashrc
fi
export PROMPT_COMMAND="history -a"
export PS1='\w: $(parse_git_branch)\n[\u@\[\e[32;40m\]\h\[\e[0m\]]'
