syntax on
" Almost all configuration options are done through plugins
set ruler
set autoindent
" These are my defaults, override in the indent files if necessary
set expandtab
set tabstop=2
set shiftwidth=2

filetype plugin indent on
let s:uname = system("uname")

" Helps with copy/paste when using autoindent
if s:uname == "Darwin\n"
  nmap <F1> :set paste<CR>:r !pbpaste<CR>:set nopaste<CR>
  imap <F1> <Esc>:set paste<CR>:r !pbpaste<CR>:set nopaste<CR>
endif
if s:uname == "Linux\n"
  nmap <C-N> :set paste<CR>i
  imap <C-N> <Esc>:set paste<CR>i
  nmap <C-B> :set nopaste<CR>
  imap <C-B> <Esc>:set nopaste<CR>
endif
